version: '2' #defining docker-compose version

networks: 
  database:
  web:
  queue_net:

volumes: 
  data-volume:

services: #Defining services (containers) to be managed by compose
  db:
    image: postgres:9.6
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: root
    volumes: 
      #Data Volume
      - data-volume:/var/lib/postgresql/data
      #Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database

  frontend:
    image: nginx:1.13
    ports: 
      - 80:80
    volumes: 
      #WebSite
      - ./web:/usr/share/nginx/html
      #Reverse Proxy config.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - web
    depends_on: 
      - app
  
  app:
    image: python:3.6
    working_dir: /app #Defines the main working directory
    command: bash ./app.sh
    volumes: 
      #Application
      - ./app:/app
    networks: 
      - database
      - web
    depends_on: 
      - db
